"""Type stubs for the compiled ``pyrust_template._core`` extension.

Compiled modules carry no inline type information, so editors and type
checkers (mypy, pyright) read this stub instead. Keep it in sync with the
signatures defined in ``src/lib.rs``.
"""

from collections.abc import Sequence

__version__: str

def add(a: int, b: int) -> int: ...
def dot(a: Sequence[float], b: Sequence[float]) -> float: ...
def cumulative_sum(values: Sequence[float]) -> list[float]: ...

class Accumulator:
    def __init__(self, start: float = ...) -> None: ...
    @property
    def total(self) -> float: ...
    def add(self, value: float) -> float: ...
    def reset(self, start: float = ...) -> None: ...
    def __repr__(self) -> str: ...
